steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$TAG_NAME'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$TAG_NAME'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$TAG_NAME'
      - '--app=$_K8S_APP_NAME'
      - '--version=$TAG_NAME'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$TAG_NAME'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DOCKERFILE_DIR: ''
  _K8S_APP_NAME: gpd-api
  _IMAGE_NAME: gcr.io/gpd-mgmt-np/github.com/soonland/tpl-dev-api
  _GKE_LOCATION: northamerica-northeast1
  _K8S_ANNOTATIONS: gcb-trigger-id=be2ee7b0-ffb7-4516-bb32-6b6b37d77efd
  _GKE_CLUSTER: autopilot-cluster-1
  _K8S_YAML_PATH: kubernetes/
  _DOCKERFILE_NAME: Dockerfile
  _OUTPUT_BUCKET_PATH: gpd-mgmt-np_cloudbuild/deploy
  _K8S_NAMESPACE: default
  _K8S_LABELS: ''
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
